title: Digital Belajar - Bahasa Latin
description: Repositori catatan belajar Bahasa Latin
domain: digital-belajar.github.io
url: http://digital-belajar.github.io/digital-belajar-latin
github_username: digital-belajar

remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
